### PR TITLE
fix fact if falcon_facts is nil

### PR DESCRIPTION
**Pull request by fe80**
Hello,

If falcon_facts is nil the fact fail:
Error: Facter: error while resolving custom fact "falcon_sensor": undefined method `reject' for nil:NilClass

Regards,

### CODE REVIEW

**Comment by 104ru** [comment]
Thank you for the input, but I don't think this is a real solution to a problem. The only reason why this error may occur is when CrowdStrike changes the format of falconctl output. When this happens, it indeed breaks the fact and the module as whole. At least as it is currently written. Suggested change does fix the fact, but the module remains broken as it would repeatedly attempt to re-register the agent. I think it is not a desired result. The best solution to this situation is to update the module to handle the changed falconctl output format.

I think the real question here is how should a module behave if the underlying software breaks it? I think the only real requirement is that a broken module does not harm the system i.e. does not alter the configuration of the software and (optionally) allow Puppet to maintain the configuration of everything else. Probably the most graceful way would be for the facter to return a value flagging the fact as broken and for the Puppet code to handle the error by stopping the management of the CrowdStrike agent (i.e. if the fact is broken, do not do anything) with or without a notification to the user. The notification is useful as a warning that the module stopped doing its job, but it would prevent Puppet from running clean. I would appreciate your view on this subject. Thanks again for you help with improving the module.

**Comment by fe80** [comment]
Hello,

Thanks for your reply. In my case it's just agent how is install without the puppet module. In my case, some customers can install/manage the crowdstrike agent without the module

**Comment by 104ru** [comment]
Sorry, you lost me there. What exactly are the circumstances when you get this facter error? The module should work no matter if CrowdStike has been install using Puppet or manually.

**Comment by fe80** [comment]
I've this fact error with a node how have the CrowdStike agent, but I don't know if it's works because I not manage it

**Comment by 104ru** [comment]
I see. Please update the module to the version 1.2.4 or newer to fix the error. It has been caused by CrowdStrike changing the format of the falconctl output, which is accounted for in the newer versions of the module.

**Pull request closed without merging**
