### PR TITLE
Plans support

### PR DESCRIPTION
**Pull request by nvergottini**
Add source parameter to crowdstrike class to allow installing from local package file rather than using system repository.

Add plans for installing or removing Falcon Sensor using Bolt.

### CODE REVIEW

**Comment by 104ru** [comment]
@nvergottini Thanks for the contribution, but I don't think that proposed enhancements are in the scope of this module or helpful enough to be included. I do not see a reason to replicate the code of the module in a plan, while you can use the code of the module directly with bolt. All you need to write a dozen lines of yaml. In general orchestration plans are usually not included in the module code since they tend to be very environment-specific and include other things besides deployment of a single module.

As for using a local package source, it seems counterproductive to me as well. How would the package get there? If you are pushing it with bolt (not a nice overhead here), then you can add another few lines of yaml to get the package installed and use the module just to do the configuration and reporting back. My thinking is that module should either just assume that the package is available in your private repo, which is not hard to do, or have some publicly available source, like in Tomcat module, for instance. 

I am happy to be convinced otherwise, but so far it seems to me that suggested features should not be included.

**Comment by nvergottini** [comment]
The use case for the plans are for a DMZ where I cannot use a traditional Puppet deployment and do not have access to internal Yum repositories. I need to be able push the agent to my servers. The local package source is specifically to support the install plan. I'm not entirely sure what you mean by replicating code of the module in the plan since I don't see that I did that. I am still using the class provided by the module to do the installation within plan. I'm not sure what you mean by orchestration plans are usually not include in the module code since I see many modules that include plans.

Please note that I'm just starting out with Bolt, so I might be taking the wrong approach. I needed a way to deploy CrowdStrike to my servers in the DMZ that I cannot manage with my Puppet Enterprise environment. I found your module, but I didn't see a way to make it work with Bolt without access to internal Yum repositories and I wanted to avoid setting up a Yum repository within the DMZ. Having a plan that will upload the package and then apply a Puppet manifest seemed like an obvious solution, but I couldn't make it work without at least adding the option to deploy from a local package. It then occurred to me that including the plans within the module was generic enough that it could be useful to others.

Regardless, I am going to use your module for installing CrowdStrike on my internal servers rather than using my existing code. For that, your module works great without modifications.

**Comment by 104ru** [comment]
Thank you for giving an example of the use case you had in mind. It sort of makes my case for me. The limitations you have to work around are very specific to your environment and I still think should stay outside the module in a plan you develop exclusively for your environment. I am not much of a bolt user myself, so I went through a good deal of "supported and approved" modules on the forge and I'd say that while many of them have tasks, only a couple of them have plans. The ones that do, have them for a very good reason of orchestrating the module's own tasks. 

I would suggest to create a plan for your specific environment, which would include the uploading of the package to the target, installation of the package and, finally, application of a module with parameters suitable for your use case. Since the module checks for an existing installation, it should not cause any conflicts.

**Comment by nvergottini** [comment]
Thanks for the response. After some thought, I think I can make your module work as is using a local file based yum repo. I can use Bolt to upload the repo ahead of doing an apply using your crowdstrike class.

**Pull request closed without merging**
